/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AirtightItem: typeof import('./src/components/featureItems/AirtightItem.vue')['default']
    BackHome: typeof import('./src/components/back-home/BackHome.vue')['default']
    BathList: typeof import('./src/components/bath/BathList.vue')['default']
    BrandClassicFancybox: typeof import('./src/components/brand/BrandClassicFancybox.vue')['default']
    BrandTeamFancyBg: typeof import('./src/components/brand/BrandTeamFancyBg.vue')['default']
    BrandTeamFancyBox: typeof import('./src/components/brand/BrandTeamFancyBox.vue')['default']
    BuildingNav: typeof import('./src/components/nav/BuildingNav.vue')['default']
    BWTItem: typeof import('./src/components/featureItems/BWTItem.vue')['default']
    DevelopNav: typeof import('./src/components/nav/DevelopNav.vue')['default']
    Elevator: typeof import('./src/components/featureItems/Elevator.vue')['default']
    ElevatorItem: typeof import('./src/components/featureItems/ElevatorItem.vue')['default']
    EntranceDoor: typeof import('./src/components/featureItems/EntranceDoor.vue')['default']
    FadeIn: typeof import('./src/components/transition/FadeIn.vue')['default']
    FadeInItem: typeof import('./src/components/transition/FadeInItem.vue')['default']
    FadeInRightToLeft: typeof import('./src/components/transition/FadeInRightToLeft.vue')['default']
    FancyContainer: typeof import('./src/components/UI/FancyContainer.vue')['default']
    FlexCol: typeof import('./src/components/UI/FlexCol.vue')['default']
    FlexRow: typeof import('./src/components/UI/FlexRow.vue')['default']
    FullScreen: typeof import('./src/components/full-screen/FullScreen.vue')['default']
    GuaranteeItem: typeof import('./src/components/featureItems/GuaranteeItem.vue')['default']
    Kitchen: typeof import('./src/components/kitchen/Kitchen.vue')['default']
    KitchenList: typeof import('./src/components/kitchen/KitchenList.vue')['default']
    LoanResult: typeof import('./src/components/loan/LoanResult.vue')['default']
    MentionTxt: typeof import('./src/components/UI/MentionTxt.vue')['default']
    Menu: typeof import('./src/components/menu/Menu.vue')['default']
    MrtFancybox: typeof import('./src/components/mrt/MrtFancybox.vue')['default']
    Nav: typeof import('./src/components/nav/Nav.vue')['default']
    PageFixed: typeof import('./src/components/pageFixed/PageFixed.vue')['default']
    RedPoint: typeof import('./src/components/point/RedPoint.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SystemItem: typeof import('./src/components/featureItems/SystemItem.vue')['default']
    WaterFilter: typeof import('./src/components/featureItems/WaterFilter.vue')['default']
    WoodenFloor: typeof import('./src/components/featureItems/WoodenFloor.vue')['default']
    WoodFloor: typeof import('./src/components/featureItems/WoodFloor.vue')['default']
  }
}
