/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackHome: typeof import('./src/components/back-home/BackHome.vue')['default']
    BuildingNav: typeof import('./src/components/nav/BuildingNav.vue')['default']
    FadeIn: typeof import('./src/components/transition/FadeIn.vue')['default']
    FadeInItem: typeof import('./src/components/transition/FadeInItem.vue')['default']
    FullScreen: typeof import('./src/components/full-screen/FullScreen.vue')['default']
    LoanResult: typeof import('./src/components/loan/LoanResult.vue')['default']
    Menu: typeof import('./src/components/menu/Menu.vue')['default']
    Nav: typeof import('./src/components/nav/Nav.vue')['default']
    PageFixed: typeof import('./src/components/pageFixed/PageFixed.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
